[tool]
name = "Flick"
version = "0.1.0"
script = "./src/main.lua"
icon = "./icon.png"

[[property]]
id = "strength"

name = "Strength"
tooltip = "How strongly you flick"

input_type = "slider"

default_value = 10.0
min_value = 2.0
max_value = 10000.0

[[property]]
id = "scale_strength_with_mass"

name = "Scale strength with mass"
tooltip = "With this, objects are flicked equally as easily regardless of how heavy they are"

input_type = "toggle"

default_value = false
