[tool]
name = "Hinge"
version = "0.1.0"
script = "./src/main.lua"
icon = "./icon.png"

[[property]]
id = "move_object"

name = "Move first object"
tooltip = "Move the first object by the amount the cursor moved during the click to ensure both objects overlap"

input_type = "toggle"

default_value = true
