[tool]
name = "Text"
version = "0.1.0"
script = "./src/main.lua"
icon = "./icon.png"

[[property]]
id = "text"

name = "Text"
tooltip = "Absolute cinema"

input_type = "text"

default_value = "Sample text"
