[tool]
name = "Box"
version = "0.1.0"
script = "./src/main.lua"
icon = "./icon.png"

[[property]]
id = "uranium"

name = "Put uranium in the box"
tooltip = "With this, objects are moved equally as easily regardless of how heavy they are"

input_type = "toggle"

default_value = false
